WITH PRODUCTOS_PAGNIFIQUE AS (

    SELECT
        DISTINCT ARTC_ARTC_ID
    FROM 
        MSTRDB.DWH.FT_VENTAS AS FV
    WHERE
        FV.PROV_PROV_ID = 5240
        AND YEAR(FV.TIEM_DIA_ID) BETWEEN 2015 AND YEAR(CURRENT_DATE())

),

TICKETS_GRAL AS (

    SELECT 
        *
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
    WHERE
        FV.TIEM_DIA_ID BETWEEN DATE_TRUNC('MONTH', CURRENT_DATE) - INTERVAL '1 MONTH' AND LAST_DAY(DATE_TRUNC('MONTH', CURRENT_DATE) - INTERVAL '1 MONTH')
        AND FV.GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)

),

TICKETS_PAGNIFIQUE AS (

    SELECT 
        *
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
    WHERE
        ARTC_ARTC_ID IN (SELECT * FROM PRODUCTOS_PAGNIFIQUE)
        AND FV.TIEM_DIA_ID BETWEEN DATE_TRUNC('MONTH', CURRENT_DATE) - INTERVAL '1 MONTH' AND LAST_DAY(DATE_TRUNC('MONTH', CURRENT_DATE) - INTERVAL '1 MONTH')
        AND FV.GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)
)

SELECT
    LGL.GEOG_LOCL_COD AS COD_LOCAL,
    MONTH(GRAL.TIEM_DIA_ID) AS MES_ANTERIOR,
    ROUND((COUNT(DISTINCT(PAG.TICKET)) / COUNT(DISTINCT(GRAL.TICKET))), 5) AS PORC_PENETRACION_TICKET,
    ROUND(SUM(PAG.VNTA_IMPORTE_SIN_IVA) / SUM(GRAL.VNTA_IMPORTE_SIN_IVA), 5) AS PORC_PENETRACION_VENTAS
FROM
    TICKETS_GRAL AS GRAL
    LEFT JOIN TICKETS_PAGNIFIQUE AS PAG ON PAG.TICKET = GRAL.TICKET AND PAG.TIEM_DIA_ID = GRAL.TIEM_DIA_ID  AND PAG.ARTC_ARTC_ID = GRAL.ARTC_ARTC_ID
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON GRAL.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
GROUP BY
    COD_LOCAL,
    MES_ANTERIOR
ORDER BY
    COD_LOCAL,
    MES_ANTERIOR DESC;