WITH PRODUCTOS_PAGNIFIQUE AS (

    SELECT
        DISTINCT ARTC_ARTC_ID
    FROM 
        MSTRDB.DWH.FT_VENTAS AS FV
    WHERE
        FV.PROV_PROV_ID = 5240
        AND YEAR(FV.TIEM_DIA_ID) BETWEEN 2015 AND YEAR(CURRENT_DATE())

),

TICKETS_GRAL AS (

    SELECT 
        FV.TIEM_DIA_ID,
        FV.TICKET,
        FV.ARTC_ARTC_ID,
        FV.GEOG_LOCL_ID,
        FV.VNTA_IMPORTE_CON_IVA,
        FV.VNTA_IMPORTE_SIN_IVA,
        FV.VNTA_UNIDADES
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
    WHERE
        FV.TIEM_DIA_ID BETWEEN DATEADD(DAY, -6, CURRENT_DATE - 1) AND CURRENT_DATE - 1
        AND FV.GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)
        AND FV.VNTA_UNIDADES > 0

),

TICKETS_PAGNIFIQUE AS (

    SELECT 
        FV.TIEM_DIA_ID,
        FV.TICKET,
        FV.ARTC_ARTC_ID,
        FV.GEOG_LOCL_ID,
        FV.VNTA_IMPORTE_CON_IVA,
        FV.VNTA_IMPORTE_SIN_IVA,
        FV.VNTA_UNIDADES,
        CASE
            WHEN IM.STANDARD_UOM = 'EA' THEN 'UNIDAD'
            ELSE 'KG'
        END AS MEDIDA        
    FROM
        MSTRDB.DWH.FT_VENTAS AS FV
        INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON FV.ARTC_ARTC_ID = LAA.ARTC_ARTC_ID
        INNER JOIN MSTRDB.DWH.ITEM_MASTER AS IM ON IM.ITEM = LAA.ORIN
    WHERE
        FV.ARTC_ARTC_ID IN (SELECT * FROM PRODUCTOS_PAGNIFIQUE)
        AND FV.TIEM_DIA_ID BETWEEN DATEADD(DAY, -6, CURRENT_DATE - 1) AND CURRENT_DATE - 1
        AND FV.GEOG_LOCL_ID IN (SELECT GEOG_LOCL_ID FROM MSTRDB.DWH.LU_GEOG_LOCAL WHERE GEOG_UNNG_ID = 2)
        AND FV.VNTA_UNIDADES > 0
),

PENETRACION_KG AS (

    SELECT 
        TP.TIEM_DIA_ID,
        TP.MEDIDA,
        TP.GEOG_LOCL_ID,
        LGL.GEOG_LOCL_COD,
        COUNT(DISTINCT(TP.TICKET)) AS TICKETS,
        SUM(TP.VNTA_UNIDADES) AS UNIDADES,
        ROUND((UNIDADES/TICKETS), 3) AS PENETRACION_KG
    FROM
        TICKETS_PAGNIFIQUE AS TP
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON TP.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
    WHERE
        MEDIDA = 'KG'
    GROUP BY
        1,2,3,4 
),

PENETRACION_UNID AS (

    SELECT 
        TP.TIEM_DIA_ID,
        TP.MEDIDA,
        TP.GEOG_LOCL_ID,
        LGL.GEOG_LOCL_COD,
        COUNT(DISTINCT(TP.TICKET)) AS TICKETS,
        SUM(TP.VNTA_UNIDADES) AS UNIDADES,
        ROUND((UNIDADES/TICKETS), 3) AS PENETRACION_UNID
    FROM
        TICKETS_PAGNIFIQUE AS TP
        INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON TP.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
    WHERE
        MEDIDA = 'UNIDAD'
    GROUP BY
        1,2,3,4    
)

SELECT
    LGL.GEOG_LOCL_COD AS COD_LOCAL,
    GRAL.TIEM_DIA_ID AS DIA,
    ROUND((COUNT(DISTINCT(PAG.TICKET)) / COUNT(DISTINCT(GRAL.TICKET))), 5) AS PORC_PENETRACION_TICKET,
    ROUND(SUM(PAG.VNTA_IMPORTE_SIN_IVA) / SUM(GRAL.VNTA_IMPORTE_SIN_IVA), 5) AS PORC_PENETRACION_VENTAS,
    KG.PENETRACION_KG AS PENETRACION_POR_KILO,
    UNID.PENETRACION_UNID AS PENETRACION_POR_UNIDAD
FROM
    TICKETS_GRAL AS GRAL
    LEFT JOIN TICKETS_PAGNIFIQUE AS PAG ON PAG.TICKET = GRAL.TICKET AND PAG.TIEM_DIA_ID = GRAL.TIEM_DIA_ID  AND PAG.ARTC_ARTC_ID = GRAL.ARTC_ARTC_ID
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON GRAL.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
    INNER JOIN PENETRACION_KG AS KG ON GRAL.TIEM_DIA_ID = KG.TIEM_DIA_ID AND GRAL.GEOG_LOCL_ID = KG.GEOG_LOCL_ID
    INNER JOIN PENETRACION_UNID AS UNID ON GRAL.TIEM_DIA_ID = UNID.TIEM_DIA_ID AND GRAL.GEOG_LOCL_ID = UNID.GEOG_LOCL_ID
GROUP BY
    COD_LOCAL,
    DIA,
    PENETRACION_POR_KILO,
    PENETRACION_POR_UNIDAD
ORDER BY
    COD_LOCAL,
    DIA DESC