WITH DESCUENTOS AS (
    SELECT
        CAMP_PROM_ID,
        VNTA_CODIGO_PROMOCION,
        A.CAMP_PROM_ESPECIFICACION,
        A.GEO_PROMOTION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS PAZOS_CODIGO_PROMO
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        (A.CAMP_PROM_ESPECIFICACION ILIKE '%pagnifique%' OR A.CAMP_PROM_NOMBRE ILIKE '%agni%')
        AND A.CAMP_PROM_OBJETIVO like '%Promocion%'
    ORDER BY
        1
), 
IMPACTADOS_BASE AS (
    SELECT
        CAMP_PROM_ID,
        YEAR(FECHA_CARGA) AS ANIO,
        MONTH(FECHA_CARGA) AS MES,
        COUNT(DISTINCT SOCI_SOCI_ID) AS TOTAL_IMPACTADOS
    FROM
        SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    GROUP BY
        ALL
),
PRODUCTOS_DESCUENTOS AS (
    SELECT
        A.CAMP_PROM_ID,
        A.ARTC_ARTC_ID,
        B.PAZOS_CODIGO_PROMO,
        B.CAMP_PROM_ESPECIFICACION,
        B.CAMP_PROM_FINI,
        B.CAMP_PROM_FFIN
    FROM
        SANDBOX_PLUS.DWH.DETALLE_ARTICULOS A
        INNER JOIN DESCUENTOS B ON A.CAMP_PROM_ID = B.CAMP_PROM_ID
    ORDER BY
        1,
        2
), 
TICKETS AS (
    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
        INNER JOIN DESCUENTOS B ON ( A.VNTA_COD_DESCUENTO::VARCHAR = B.VNTA_CODIGO_PROMOCION 
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_CODIGO::VARCHAR = B.VNTA_CODIGO_PROMOCION
                OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL
                OR A.VNTA_CODIGO::VARCHAR = B.GEO_PROMOTION AND B.GEO_PROMOTION IS NOT NULL) 
            AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) > 2023
), 
USOS_PROMO_FALLIDA AS (
    SELECT
        Inner_Select.ANIO,
        Inner_Select.MES,
        Inner_Select.PROMO,
        Inner_Select.CAMP_PROM_FINI,
        Inner_Select.CAMP_PROM_FFIN,
        COUNT(DISTINCT(Inner_Select.TICKET)) AS TICKETS,
        SUM(Inner_Select.VNTA_IMPORTE_CON_IVA_NEW) AS VNTA_IMPORTE_CON_IVA,
        COUNT(DISTINCT(Inner_Select.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        -- Sumamos las dos nuevas columnas manteniendo el orden para el UNION
        MAX(COALESCE(I.TOTAL_IMPACTADOS, 0)) AS CLIENTES_IMPACTADOS,
        ROUND(100 * COUNT(DISTINCT(Inner_Select.SOCI_SOCI_ID)) / NULLIF(MAX(COALESCE(I.TOTAL_IMPACTADOS, 0)), 0), 2) AS TASA_REDENCION_PORC
    FROM
        (
            SELECT
                YEAR(FV.TIEM_DIA_ID) ANIO,
                MONTH(FV.TIEM_DIA_ID) MES,
                DA.CAMP_PROM_ID,
                DP.CAMP_PROM_ESPECIFICACION AS PROMO,
                DP.CAMP_PROM_FINI,
                DP.CAMP_PROM_FFIN,
                FV.TICKET,
                FFM.SOCI_SOCI_ID,
                CASE
                    WHEN FV.ARTC_ARTC_ID = 25960 THEN 59
                    ELSE 99
                END AS VNTA_IMPORTE_CON_IVA_NEW,
                FV.VNTA_IMPORTE_CON_IVA,
                FV.ARTC_ARTC_ID,
                LAA.ARTC_ARTC_DESC
            FROM
                MSTRDB.DWH.FT_VENTAS AS FV
                INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET
                INNER JOIN SANDBOX_PLUS.DWH.DETALLE_ARTICULOS AS DA ON FV.ARTC_ARTC_ID = DA.ARTC_ARTC_ID AND DA.CAMP_PROM_ID IN (752, 753)
                INNER JOIN SANDBOX_PLUS.DWH.DETALLE_PROMO AS DP ON DA.CAMP_PROM_ID = DP.CAMP_PROM_ID
                INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
                INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON LAA.ARTC_ARTC_ID = FV.ARTC_ARTC_ID
                INNER JOIN MSTRDB.DWH.LU_CLIE_CLIENTE AS LCC ON LCC.SOCI_SOCI_ID = FFM.SOCI_SOCI_ID
            WHERE
                FFM.SOCI_SOCI_ID IN (SELECT DISTINCT SOCI_SOCI_ID FROM SANDBOX_PLUS.DWH.DETALLE_CLIENTES WHERE YEAR(FECHA_CARGA) = YEAR(CURRENT_DATE()) AND MONTH(FECHA_CARGA) = 10 AND CAMP_PROM_ID IN (753))
                AND FFM.TIEM_DIA_ID BETWEEN '2023-10-06' AND '2023-10-17'
                AND FV.ARTC_ARTC_ID IN (SELECT DISTINCT ARTC_ARTC_ID FROM SANDBOX_PLUS.DWH.DETALLE_ARTICULOS WHERE CAMP_PROM_ID IN (752, 753))
                AND FV.VNTA_UNIDADES > 0
        ) Inner_Select
    LEFT JOIN IMPACTADOS_BASE I ON Inner_Select.CAMP_PROM_ID = I.CAMP_PROM_ID AND Inner_Select.ANIO = I.ANIO AND Inner_Select.MES = I.MES
    GROUP BY
        1, 2, 3, 4, 5
)
SELECT
    *
FROM
    (
        (SELECT
            YEAR(FV.TIEM_DIA_ID) ANIO,
            MONTH(FV.TIEM_DIA_ID) MES,
            TIC.CAMP_PROM_ESPECIFICACION AS PROMO,
            TIC.CAMP_PROM_FINI,
            TIC.CAMP_PROM_FFIN,
            COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
            SUM(FV.VNTA_IMPORTE_SIN_IVA) AS VTA_PROMO,
            COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
            -- Sumamos las dos nuevas columnas manteniendo el orden para el UNION
            MAX(COALESCE(I.TOTAL_IMPACTADOS, 0)) AS CLIENTES_IMPACTADOS,
            ROUND(100 * COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) / NULLIF(MAX(COALESCE(I.TOTAL_IMPACTADOS, 0)), 0), 2) AS TASA_REDENCION_PORC
        FROM
            MSTRDB.DWH.FT_VENTAS AS FV
            INNER JOIN TICKETS AS TIC ON FV.TICKET = TIC.TICKET AND FV.TIEM_DIA_ID = TIC.TIEM_DIA_ID
            INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TICKET = FFM.TICKET AND FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID
            INNER JOIN PRODUCTOS_DESCUENTOS AS PD ON FV.ARTC_ARTC_ID = PD.ARTC_ARTC_ID AND TIC.CAMP_PROM_ID = PD.CAMP_PROM_ID
            LEFT JOIN IMPACTADOS_BASE I ON TIC.CAMP_PROM_ID = I.CAMP_PROM_ID AND YEAR(FV.TIEM_DIA_ID) = I.ANIO AND MONTH(FV.TIEM_DIA_ID) = I.MES
        WHERE
            YEAR(FV.TIEM_DIA_ID) > 2021
            AND FFM.FDLN_MOVT_TIPO = 'RP'
        GROUP BY
            1, 2, 3, 4, 5)

        UNION ALL

        (SELECT * FROM USOS_PROMO_FALLIDA)
    )
ORDER BY
    1 DESC,
    2 DESC,
    4 DESC,
    5,
    3;