
WITH DESCUENTOS AS (
    SELECT
        CAMP_PROM_ID,
        VNTA_CODIGO_PROMOCION,
        A.CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        COALESCE(PAZOS_CODIGO_PROMO, VNTA_CODIGO_PROMOCION) AS PAZOS_CODIGO_PROMO,
        GEO_PROMOTION
    FROM
        SANDBOX_PLUS.DWH.DETALLE_PROMO AS A
        LEFT JOIN MSTRDB.DWH.LU_PROMO_RPM AS L on L.RPM_CODIGO_PROMO = A.VNTA_CODIGO_PROMOCION
    WHERE
        (A.CAMP_PROM_ESPECIFICACION ILIKE '%pagnifique%' OR A.CAMP_PROM_NOMBRE ILIKE '%agni%')
        AND A.CAMP_PROM_OBJETIVO like '%Promocion%'
),
PRODUCTOS_DESCUENTOS AS (
    SELECT
        A.CAMP_PROM_ID,
        A.ARTC_ARTC_ID,
        B.PAZOS_CODIGO_PROMO,
        B.CAMP_PROM_ESPECIFICACION,
        B.CAMP_PROM_FINI,
        B.CAMP_PROM_FFIN
    FROM
        SANDBOX_PLUS.DWH.DETALLE_ARTICULOS A
        INNER JOIN DESCUENTOS B ON A.CAMP_PROM_ID = B.CAMP_PROM_ID
),
TICKETS AS (
    SELECT
        DISTINCT
        TIEM_DIA_ID,
        VNTA_COD_DESCUENTO,
        VNTA_NRO_CAJA,
        VNTA_NRO_TICKET,
        GEOG_LOCL_ID,
        TICKET,
        CAMP_PROM_ID,
        CAMP_PROM_ESPECIFICACION,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN
    FROM
        MSTRDB.DWH.FT_VENTAS_DESCUENTOS_LINEAS A
        INNER JOIN DESCUENTOS B ON (
            A.VNTA_COD_DESCUENTO::VARCHAR = B.PAZOS_CODIGO_PROMO
            OR A.VNTA_COD_BENEFICIO_DESCUENTO::VARCHAR = B.PAZOS_CODIGO_PROMO
            OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.PAZOS_CODIGO_PROMO
            OR A.VNTA_COD_DESCUENTO::VARCHAR = B.GEO_PROMOTION
            OR A.VNTA_COD_BENEFICIO_DESCUENTO::VARCHAR = B.GEO_PROMOTION
            OR A.VNTA_CODIGO_PROMOCION::VARCHAR = B.GEO_PROMOTION
        ) 
            AND A.TIEM_DIA_ID BETWEEN B.CAMP_PROM_FINI AND B.CAMP_PROM_FFIN
    WHERE
        YEAR(TIEM_DIA_ID) > 2021
),
POB_IMPACTADOS AS (
    SELECT 
        CAMP_PROM_ID,
        COUNT(DISTINCT SOCI_SOCI_ID) AS TOTAL_IMPACTADOS
    FROM SANDBOX_PLUS.DWH.DETALLE_CLIENTES
    GROUP BY ALL
),
USOS_PROMO_FALLIDA AS (
    SELECT
        ANIO,
        MES,
        PROMO,
        CAMP_PROM_FINI,
        CAMP_PROM_FFIN,
        COUNT(DISTINCT(TICKET)) AS TICKETS,
        SUM(VNTA_IMPORTE_CON_IVA_NEW) AS VNTA_IMPORTE_CON_IVA,
        COUNT(DISTINCT(SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
        COALESCE(MAX(IMPACTADOS_C), 0) AS IMPACTADOS,
        ROUND(100 * COUNT(DISTINCT(SOCI_SOCI_ID)) / NULLIF(COALESCE(MAX(IMPACTADOS_C), 0), 0), 2) AS PORC_REDENCION
    FROM
        (
            SELECT
                YEAR(FV.TIEM_DIA_ID) ANIO,
                MONTH(FV.TIEM_DIA_ID) MES,
                DP.CAMP_PROM_ESPECIFICACION AS PROMO,
                DP.CAMP_PROM_FINI,
                DP.CAMP_PROM_FFIN,
                FV.TICKET,
                FFM.SOCI_SOCI_ID,
                CASE
                    WHEN FV.ARTC_ARTC_ID = 25960 THEN 59
                    ELSE 99
                END AS VNTA_IMPORTE_CON_IVA_NEW,
                COALESCE(PI.TOTAL_IMPACTADOS, 0) AS IMPACTADOS_C
            FROM
                MSTRDB.DWH.FT_VENTAS AS FV
                INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID AND FV.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID AND FV.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA AND FV.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
                INNER JOIN SANDBOX_PLUS.DWH.DETALLE_ARTICULOS AS DA ON FV.ARTC_ARTC_ID = DA.ARTC_ARTC_ID AND DA.CAMP_PROM_ID IN (752, 753)
                INNER JOIN SANDBOX_PLUS.DWH.DETALLE_PROMO AS DP ON DA.CAMP_PROM_ID = DP.CAMP_PROM_ID
                INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FV.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID
                INNER JOIN MSTRDB.DWH.LU_ARTC_ARTICULO AS LAA ON LAA.ARTC_ARTC_ID = FV.ARTC_ARTC_ID
                INNER JOIN MSTRDB.DWH.LU_CLIE_CLIENTE AS LCC ON LCC.SOCI_SOCI_ID = FFM.SOCI_SOCI_ID
                LEFT JOIN POB_IMPACTADOS PI ON DA.CAMP_PROM_ID = PI.CAMP_PROM_ID
            WHERE
                FFM.SOCI_SOCI_ID IN (SELECT DISTINCT SOCI_SOCI_ID FROM SANDBOX_PLUS.DWH.DETALLE_CLIENTES WHERE YEAR(FECHA_CARGA) = YEAR(CURRENT_DATE()) AND MONTH(FECHA_CARGA) = 10 AND CAMP_PROM_ID IN (753))
                AND FFM.TIEM_DIA_ID BETWEEN '2023-10-06' AND '2023-10-17'
                AND FV.ARTC_ARTC_ID IN (SELECT DISTINCT ARTC_ARTC_ID FROM SANDBOX_PLUS.DWH.DETALLE_ARTICULOS WHERE CAMP_PROM_ID IN (752, 753))
                AND FV.VNTA_UNIDADES > 0
        )
    GROUP BY
        1, 2, 3, 4, 5
)
SELECT
    *
FROM
    (
        (SELECT
            YEAR(FV.TIEM_DIA_ID) ANIO,
            MONTH(FV.TIEM_DIA_ID) MES,
            TIC.CAMP_PROM_ESPECIFICACION AS PROMO,
            TIC.CAMP_PROM_FINI,
            TIC.CAMP_PROM_FFIN,
            COUNT(DISTINCT(FV.TICKET)) AS TICKETS,
            SUM(FV.VNTA_IMPORTE_SIN_IVA) AS VTA_PROMO,
            COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS_CON_PROMO,
            COALESCE(PI.TOTAL_IMPACTADOS, 0) AS IMPACTADOS,
            ROUND(100 * COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) / NULLIF(COALESCE(PI.TOTAL_IMPACTADOS, 0), 0), 2) AS PORC_REDENCION
        FROM
            MSTRDB.DWH.FT_VENTAS AS FV
            INNER JOIN TICKETS AS TIC ON FV.TIEM_DIA_ID = TIC.TIEM_DIA_ID AND FV.GEOG_LOCL_ID = TIC.GEOG_LOCL_ID AND FV.VNTA_NRO_CAJA = TIC.VNTA_NRO_CAJA AND FV.VNTA_NRO_TICKET = TIC.VNTA_NRO_TICKET
            INNER JOIN MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM ON FV.TIEM_DIA_ID = FFM.TIEM_DIA_ID AND FV.GEOG_LOCL_ID = FFM.GEOG_LOCL_ID AND FV.VNTA_NRO_CAJA = FFM.VNTA_NRO_CAJA AND FV.VNTA_NRO_TICKET = FFM.VNTA_NRO_TICKET
            INNER JOIN PRODUCTOS_DESCUENTOS AS PD ON FV.ARTC_ARTC_ID = PD.ARTC_ARTC_ID AND TIC.CAMP_PROM_ID = PD.CAMP_PROM_ID
            LEFT JOIN POB_IMPACTADOS AS PI ON TIC.CAMP_PROM_ID = PI.CAMP_PROM_ID
        WHERE
            YEAR(FV.TIEM_DIA_ID) > 2021
            AND FFM.FDLN_MOVT_TIPO = 'RP'
        GROUP BY
            ALL)

        UNION

        (SELECT * FROM USOS_PROMO_FALLIDA)
    )
ORDER BY
    1 DESC,
    2 DESC,
    4 DESC,
    5,
    3;